<?php
$SubTitle = "002";
include('html_head.inc');
?>
<h1>Problem 2</h1>
<pre>
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
</pre>
<h2>Code</h2>
<pre>
$Sum = $EvenSum = $Left = 0; $Right = 1;
while ($Left + $Right &lt; 4000000):
	$Sum = $Left + $Right;
	if ($Sum % 2 == 0) $EvenSum = $EvenSum + $Sum;
	$Left = $Right; $Right = $Sum;
endwhile;
print($EvenSum);
</pre>
<h3>Result</h3>
<pre>
<?php $StartTime = microtime(TRUE); ?>
<?php
$Sum = $EvenSum = $Left = 0; $Right = 1;
while ($Left + $Right < 4000000):
	$Sum = $Left + $Right;
	if ($Sum % 2 == 0) $EvenSum = $EvenSum + $Sum;
	$Left = $Right; $Right = $Sum;
endwhile;
print($EvenSum);
?>
<?php $EndTime = microtime(TRUE); ?>
</pre>
<h3>Variables</h3>
<pre>
<?php
print("\$Sum:&nbsp;"); var_dump($Sum);
print("\$Left:&nbsp;"); var_dump($Left);
print("\$Right:&nbsp;"); var_dump($Right);
print("\$EvenSum:&nbsp;"); var_dump($EvenSum);
?>
</pre>
<h3>Execution time</h3>
<pre>
<?php
$Time = $EndTime - $StartTime;
print("{$Time} Seconds.");
?>
</pre>
<?php include('html_foot.inc'); ?> 