<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta charset="utf-8">
	<meta name="author" content="reinforchu">
	<meta name="description" content="Project Euler on PHP">
	<meta name="keywords" content="reinforchu,Project Euler,Euler,PHP">
	<meta name="robots" content="index,follow,noarchive">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="vnd.up.bookmark" p:forua="true" content="http://xn--eckk2c4f8d7b7c.jp/euler/" /><!-- XHTML has a mix that HTML5 is a known issue. This is a directive to the Japanese mobile phones. -->
	<title>Project Euler on PHP<?php if (isset($SubTitle)) print(" - {$SubTitle}"); ?></title>
	<link rel="shortcut icon" href="http://xn--eckk2c4f8d7b7c.jp/schwertkreuz.ico" type="image/vnd.microsoft.icon">
	<link rel="stylesheet" href="http://xn--eckk2c4f8d7b7c.jp/files/bootstrap/css/bootstrap.css" type="text/css">
	<link rel="stylesheet" href="http://xn--eckk2c4f8d7b7c.jp/files/bootstrap/css/bootstrap-responsive.css" type="text/css">
	<script src="http://code.jquery.com/jquery-1.7.1.js"></script>
	<script src="http://xn--eckk2c4f8d7b7c.jp/files//bootstrap/js/bootstrap.min.js"></script>
	<style type="text/css">
		body {
			color: #072766;
			background-color: #ffffff;
			background: transparent url('http://xn--eckk2c4f8d7b7c.jp/files/webx-bkg.png') repeat-x;
			margin-top: 0px;
			margin-bottom: 0px;
			margin-left: 0px;
			margin-right: 0px;
			line-height: 115%;
			font-family: 'Meiryo UI','メイリオ','ヒラギノ角ゴ Pro W3','Hiragino Kaku Gothic Pro',Tahoma;
		}
		a:link { color: #0084B4; }
		a:visited { color: #0084b4; }
		a:active { color: #269abd; }
		a:hover { color: #16d6e0; }
		hr { color: #072766; }
		img {border: none;}
		form { display: inline; }
		textarea { height: 120px; }
		#TextShadow { text-shadow: 5px 5px 15px black; }
		#BoxShadow { box-shadow: 3px 3px 5px black; }
		#MainBoxShadow { box-shadow: 2px 2px 3px black; }
		#Alpha {
			Filter: Alpha(Opacity=95);
			opacity: .95;
		}
	</style>
</head>
<body>
<!-- Fixed NavigationBar -->
<div class="navbar navbar-fixed-top" id="Alpha">
	<div class="navbar-inner" id="BoxShadow">
		<div class="container">
			<a class="brand" href="http://twitter.com/reinforchu" title="twitter" target="_blank"><img src="http://projecteuler.net/favicon.ico" alt="PElogo" width="16" height="16">&nbsp;Project&nbsp;Euler</a>
			<div class="nav-collapse">
				<ul class="nav">
					<li><a href="http://xn--eckk2c4f8d7b7c.jp/"><img src="http://xn--eckk2c4f8d7b7c.jp/schwertkreuz-project-icon.png" alt="logo" width="20" height="20">&nbsp;Home</a></li>
					<li class="active"><a href="http://xn--eckk2c4f8d7b7c.jp/euler/"><img src="http://projecteuler.net/favicon.ico" alt="PElogo" width="16" height="16">&nbsp;PE&nbsp;on&nbsp;PHP</a></li>
				</ul>
			</div><!-- nav-collapse -->
		</div><!-- container -->
	</div><!-- navbar-inner -->
</div><!-- navbar navbar-fixed-top -->
<!-- End of Fixed NavigationBar -->
<p><br><br></p>
<!-- body -->
<div class="container">
